import type { Bench, LabDatabase } from './types'

export const benches: Bench[] = [
  'Bench 1 - Blood/CSF/Stool Cultures',
  'Bench 2 - Aerobic Cultures',
  'Bench 3 - Urine Cultures',
  'Bench 4 - Respiratory Culture',
  'Bench 5 - Stool Kits + MALDI',
  'BACTEC Bench',
  'Mycology',
  'AFB',
  'Anaerobes',
  'Molecular',
  'MicroScan',
  'MALDI',
  'Set Up Bench',
  'Inventory',
  'Admin/Training',
]

export const seedData: LabDatabase = {
  benches,
  staff: [
    {
      id: 'STF-001',
      name: 'Noland Metoyer',
      role: 'Inventory Coordinator',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: ['Inventory', 'Admin/Training'],
      shiftPreference: 'Day',
      notes: 'Inventory coordination.',
      active: true,
    },
    {
      id: 'STF-002',
      name: 'Pamela Weeks',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [
        'Bench 3 - Urine Cultures',
        'Bench 4 - Respiratory Culture',
        'Bench 5 - Stool Kits + MALDI',
        'Molecular',
        'BACTEC Bench',
      ],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-003',
      name: 'Raazia Javed',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: ['BACTEC Bench', 'Bench 3 - Urine Cultures', 'Bench 5 - Stool Kits + MALDI'],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-004',
      name: 'Torrian Nolan',
      role: 'Lab Assistant',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'Lab assistant.',
      active: true,
    },
    {
      id: 'STF-005',
      name: 'Wanda Johnson',
      role: 'Clinical/Medical Lab Technician',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLT.',
      active: true,
    },
    {
      id: 'STF-006',
      name: 'Yvette Bergeron',
      role: 'Lab Education Coordinator',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: ['Admin/Training'],
      shiftPreference: 'Day',
      notes: 'Owns competency calendar.',
      active: true,
    },
    {
      id: 'STF-007',
      name: 'LaShone Francis',
      role: 'Lab Assistant',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'Lab assistant.',
      active: true,
    },
    {
      id: 'STF-008',
      name: 'Lauren Sensebe',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [
        'BACTEC Bench',
        'Bench 3 - Urine Cultures',
        'Bench 5 - Stool Kits + MALDI',
        'Molecular',
        'MicroScan',
      ],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-009',
      name: 'Melanie Fillerbe',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-010',
      name: 'Jordan Shavers',
      role: 'Lab Assistant',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'Lab assistant.',
      active: true,
    },
    {
      id: 'STF-011',
      name: 'Jose Ashby',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-012',
      name: 'Joyce Victoriano',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-013',
      name: 'Jessica Raiford',
      role: 'Clinical/Medical Lab Technician',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLT.',
      active: true,
    },
    {
      id: 'STF-014',
      name: 'Gage Weeks',
      role: 'Clinical/Medical Lab Technician',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLT.',
      active: true,
    },
    {
      id: 'STF-015',
      name: 'Jam Alino',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-016',
      name: 'Jane Jarosz',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-017',
      name: 'Jane Katherina Navora',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-018',
      name: 'Ashlee Breaux',
      role: 'Sr Medical Technologist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: ['Bench 2 - Aerobic Cultures', 'Bench 4 - Respiratory Culture', 'Anaerobes'],
      shiftPreference: 'Day',
      notes: 'Senior technologist.',
      active: true,
    },
    {
      id: 'STF-019',
      name: 'Christian Joy Aquino',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-020',
      name: 'Amany Ahmad',
      role: 'Clinical/Medical Lab Technician',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLT.',
      active: true,
    },
    {
      id: 'STF-021',
      name: 'Akia West',
      role: 'Lab Assistant',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'Lab assistant.',
      active: true,
    },
    {
      id: 'STF-022',
      name: 'Calliope Karagiannis',
      role: 'Clinical/Medical Laboratory Scientist',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLS. Placeholder competencies until approved bench assignments are entered.',
      active: true,
    },
    {
      id: 'STF-023',
      name: 'Karla Klump-Carter',
      role: 'Clinical/Medical Lab Technician',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: [],
      shiftPreference: 'Day',
      notes: 'MLT.',
      active: true,
    },
    {
      id: 'STF-024',
      name: 'Radell McMillian',
      role: 'Inventory Personnel',
      primaryLocation: 'Ochsner Medical Center - Microbiology',
      employmentStatus: 'Full-time',
      benchCompetencies: ['Inventory'],
      shiftPreference: 'Day',
      notes: 'Inventory personnel.',
      active: true,
    },
  ],
  scheduleAssignments: [
    { id: 'SCH-001', staffId: 'STF-018', date: '2026-06-18', shift: 'Day', bench: 'Bench 2 - Aerobic Cultures', notes: 'Demo bench coverage' },
    { id: 'SCH-002', staffId: 'STF-002', date: '2026-06-18', shift: 'Evening', bench: 'Bench 4 - Respiratory Culture', notes: 'Demo evening coverage' },
    { id: 'SCH-003', staffId: 'STF-003', date: '2026-06-18', shift: 'Day', bench: 'BACTEC Bench', notes: 'Demo BACTEC coverage' },
    { id: 'SCH-004', staffId: 'STF-008', date: '2026-06-18', shift: 'Day', bench: 'MicroScan', notes: 'Demo MicroScan coverage' },
    { id: 'SCH-005', staffId: 'STF-024', date: '2026-06-18', shift: 'Day', bench: 'Inventory', notes: 'Inventory support' },
    { id: 'SCH-006', staffId: 'STF-006', date: '2026-06-19', shift: 'Day', bench: 'Admin/Training', notes: 'Competency reviews' },
  ],
  competencies: [
    { id: 'CMP-001', staffId: 'STF-018', bench: 'Bench 2 - Aerobic Cultures', status: 'Competent', initialDate: '2024-05-10', annualDueDate: '2026-07-01', trainer: 'Yvette Bergeron', notes: 'Annual review scheduled.' },
    { id: 'CMP-002', staffId: 'STF-002', bench: 'Molecular', status: 'Annual review due', initialDate: '2025-04-15', annualDueDate: '2026-06-25', trainer: 'Ashlee Breaux', notes: 'Review checklist pending.' },
    { id: 'CMP-003', staffId: 'STF-008', bench: 'MicroScan', status: 'Competent', initialDate: '2026-05-20', annualDueDate: '2027-05-20', trainer: 'Pamela Weeks', notes: 'Initial competency placeholder.' },
    { id: 'CMP-004', staffId: 'STF-024', bench: 'Inventory', status: 'Competent', initialDate: '2026-06-01', annualDueDate: '2027-06-01', trainer: 'Yvette Bergeron', notes: 'Inventory support documentation competency.' },
  ],
  sops: [
    { id: 'SOP-MIC-001', title: 'Blood Culture Positive Workup', section: 'Bench 1 - Blood/CSF/Stool Cultures', version: '3.2', effectiveDate: '2026-01-15', reviewDueDate: '2026-07-15', owner: 'Pamela Weeks', status: 'Active', changeSummary: 'Updated escalation criteria and review workflow.', attachment: 'Link placeholder' },
    { id: 'SOP-MIC-014', title: 'Respiratory Culture Processing', section: 'Bench 4 - Respiratory Culture', version: '2.1', effectiveDate: '2025-11-01', reviewDueDate: '2026-06-24', owner: 'Raazia Javed', status: 'Under Review', changeSummary: 'Annual review and language cleanup.', attachment: 'Link placeholder' },
    { id: 'SOP-QC-006', title: 'Media QC and Lot Verification', section: 'Inventory', version: '1.8', effectiveDate: '2026-03-01', reviewDueDate: '2026-09-01', owner: 'Radell McMillian', status: 'Active', changeSummary: 'Added lot-to-lot verification documentation field.', attachment: 'Link placeholder' },
  ],
  tasks: [
    { id: 'TSK-001', title: 'Review temperature logs', category: 'Daily', assignedTo: 'STF-005', dueDate: '2026-06-18', priority: 'High', status: 'Open', completionDate: '', notes: 'Document reviewer initials in log.' },
    { id: 'TSK-002', title: 'Lot-to-lot verification packet', category: 'QC', assignedTo: 'STF-024', dueDate: '2026-06-21', priority: 'Critical', status: 'In Progress', completionDate: '', notes: 'Attach supporting documents.' },
    { id: 'TSK-003', title: 'New hire competency check', category: 'Training', assignedTo: 'STF-006', dueDate: '2026-06-25', priority: 'Medium', status: 'Pending Review', completionDate: '', notes: 'Preceptor comments needed.' },
  ],
  reminders: [
    { id: 'REM-001', title: 'QC due: anaerobe media', type: 'QC due', dueDate: '2026-06-19', owner: 'Pamela Weeks', status: 'Open' },
    { id: 'REM-002', title: 'Preventive maintenance review', type: 'Preventive maintenance', dueDate: '2026-06-22', owner: 'Radell McMillian', status: 'Open' },
    { id: 'REM-003', title: 'CAP/CLIA readiness huddle', type: 'CAP/CLIA readiness', dueDate: '2026-06-24', owner: 'Yvette Bergeron', status: 'Open' },
  ],
  instrumentLogs: [
    {
      id: 'INS-001',
      instrument: 'Molecular Analyzer A',
      dateTime: '2026-06-17T14:30',
      issue: 'Sample rack sensor warning',
      section: 'Molecular',
      troubleshooting: 'Checked rack seating, verified control run, executed restart, documented ticket.',
      workflowStep: 'Document',
      downtime: '35 minutes',
      vendorContacted: true,
      ticketNumber: 'TKT-000123',
      resolution: 'Returned to service after restart and acceptable controls.',
      followUpNeeded: 'Monitor next three runs.',
      documentedBy: 'Raazia Javed',
    },
  ],
  workflowImprovements: [
    {
      id: 'WFI-001',
      problem: 'Manual bench handoff notes are inconsistent between shifts.',
      proposedImprovement: 'Create structured handoff fields by bench and shift.',
      priority: 'High',
      owner: 'Pamela Weeks',
      targetDate: '2026-07-05',
      status: 'Planning',
      outcome: 'Not implemented yet.',
      followUpNotes: 'Review at staff meeting.',
    },
  ],
  qcEvents: [
    {
      id: 'QC-001',
      eventType: 'Temperature excursion review',
      section: 'Inventory',
      date: '2026-06-16',
      description: 'Incubator temperature out of range during daily review.',
      correctiveAction: 'Moved affected material, documented assessment, repeated QC where indicated.',
      responsibleStaff: 'Pamela Weeks',
      reviewStatus: 'Pending Review',
      notification: 'Supervisor notified; pathologist notification not required for placeholder event.',
      completionDate: '',
      supportingDocument: 'Document placeholder',
    },
  ],
  auditEvents: [
    {
      id: 'AUD-001',
      action: 'Seeded',
      itemType: 'System',
      itemId: 'LOCAL-MOCK-DB',
      user: 'System',
      dateTime: '2026-06-18T08:00:00',
      summary: 'Initial personnel roster and placeholder operations data loaded without PHI.',
    },
  ],
}
